<?php
/*
 * Password Banned List
 * By Matthew Simpson (http://matthewsimpson.net)
 * Copyright 2014 NB Communication (http://www.nbcommunication.com)
*/

class PasswordBannedList extends WireData implements Module {
	private $bad;

	public static function getModuleInfo() {
		return array(
			'title' => 'Password Banned List',
			'summary' => 'Check input password against a banned password file.',
			'autoload' => true,
			'version' => 1,
			'requires' => 'InputfieldPassword'
		);
	}
	
	public function init() {
		$this->bad = file(wire('config')->paths->siteModules.'PasswordBannedList/banned.list',FILE_SKIP_EMPTY_LINES|FILE_IGNORE_NEW_LINES);
		wire()->addHookAfter('InputfieldPassword::processInput',$this,'checkPass');
	}
	
	public function checkPass(Hookevent $event){
		$inputfield = $event->object;
		$password = $inputfield->attr('value');
		if(in_array($password, $this->bad)) {
			$inputfield->error('The password you entered is in the list of the 10,000 most common passwords. Please use a more secure password.');
			$inputfield->attr('value', '');
		}
	}
}
?>